name: 'Continuous Delivery'

on:
  pull_request:
    branches:
      - release
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'

    - name: Install poetry and virtualenv
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Push to production
      run: |
        bash scripts/deploy.sh

    - name: Run stress test
      run: |
        make stress-test