name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - develop
      - release
      - main

jobs:
  run_testing:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Get model
      run:
        python challenge/model.py

    - name: Run model test
      run: |
        make model-test

    - name: Run api test
      run: |
        make api-test