name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'challenge/**'
      - 'scripts/**'
      - '.github/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  my_first_job:
    runs-on: ubuntu-latest # put this in an environment?
    steps:
    - name: Python version
      run: |
        python --version
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Start poetry shell
      run: |
        poetry shell
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        make model-test