name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'challenge/**'
      - 'scripts/**'
      - '.github/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  my_first_job:
    runs-on: ubuntu-latest # put this in an environment?
    steps:
    - uses: actions/checkout@v4
    - name: Check directory
      run: |
        ls
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    - name: Python version
      run: |
        python --version
    - name: Install poetry and virtualenv
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry lock --no-update
        poetry install
    - name: Run tests
      run: |
        make model-test